---
title: "Split Decision : Understanding the Outcomes of Military Occupation in Korea"
author: "Pete Erickson"
date: |
  `r format(Sys.time(), '%B %d, %Y')`
abstract: |
  The purpose of this paper is to explain the differences in outcomes of military occupations on the Korean Peninsula after World War Two. After Japan surrendered to the United States in August, 1945, the Soviet Union occupied Korea north of the 38th parallel while the United States occupied south of the 38th parallel. The original intent of this occupation was to serve as an international "trusteeship" that would eventually lead to Korean independence. However, the legacy of Japanese colonialism proved to be a formidable foe to overcome for both the Soviet and American occupation forces. Using a principal-agent approach, this paper argues that the Soviet Union was able to more effectively establish an agent in the North Korean state under Kim Il Sung than the Americans were in the South under Syngman Rhee. As a result, the Soviets were far more successful than the Americans in achieving their respective goals on the Korean Peninsula in the years following World War Two.
  
geometry: margin = 1.15in              # margin widths
fontsize: 12pt                         # text size
bibliography: researchpaper-ps960.bib # bibliography file
biblio-style: authoryear               # citation style
urlcolor: blue                         # links to external URLs
citecolor: black                       # links to bibliography
linkcolor: magenta                     # internal figures, footnotes, etc.
indent: true                          # paragraph format
                                       # true for indented paragraphs
                                       
header-includes:
    - \usepackage{setspace}
    - \usepackage{multirow}

output: 
  bookdown::pdf_document2:
    keep_tex: true
    latex_engine: pdflatex
    number_sections: false
    toc: false
    fig_caption: true
    citation_package: biblatex
    includes: 
      in_header: 
        - latex-preamble.tex
  bookdown::htmldocument2: default
  bookdown::word_document2:
      toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\doublespacing

# Introduction

In the immediate weeks after World War Two, occupation forces from the militaries of both the Soviet Union and the United States made their way to the Korean Peninsula, each occupying respective zones, the Soviet Union in the North, and the United States south of the 38th parallel. Over the next three years, American and Soviet occupation forces made and implemented significant decisions related to their respective occupations that vastly altered the trajectory of Korean politics. 

This paper seeks to explain an interesting puzzle: why did the Soviet occupation forces have relatively more success than the American occupying forces on the Korean Peninsula after World War Two? By most accounts, the Soviet occupation is considered to have been a "successful" occupation, whereas the American occupation is considered to have achieved "mixed" results [@edelstein_occupational_2008]. Attempting to explain the difference in results of these simultaneous occupations is an interesting puzzle for several reasons. First, the occupations occurred simultaneously between 1945-1948 among a relatively homogeneous people. Though the southern and northern occupied areas had important differences in terms of industrial output and natural resources, the two areas were not vastly different at the time that the respective occupation forces arrived in 1945. Second, it is an interesting question to consider because neither side had spent a great deal planning for the occupation of Korea, as each had focused on more critical strategic goals in the waning months of World War Two. 

In this paper, I argue that the main difference in outcomes between the Soviet-led and American-led occupations can be described using a principal-agent approach. Each of the occupation forces served as principals and thus made key decisions to select agents, delegate responsibilities to these agents, and monitor the actions of these agents to ensure that these agents acted in accordance with the goals of the principals. In advancing this argument, I propose a two-level theory of military occupation which incorporates the principal-agent theory to underscore the unique challenges that military occupation forces face, particularly in the period of an occupation before a fledgling government is officially formed and recognized in the occupied country. It is in this period in particular that perhaps the most consequential decisions are made by the occupying forces acting as principals. I conclude by briefly addressing potential counterarguments and the legacy of contemporary American-led military occupations and advisory efforts in Iraq and Afghanistan.  

# Military Occupation as a Topic of Study

The study of military occupations straddles multiple disciplinary fields, including international law, history, and political science [@stirk_politics_2009]. One of the prominent works in political science on the topics of military occupations is David Edelstein's _Occupational Hazards: Success and Failure in Military Occupation_. In the book, Edelstein determines that of the 26 military occupations that have occurred since 1815, only seven have resulted in successful outcomes [@edelstein_occupational_2008]. One of the key factors that determines the success or failure of an occupation, Edelstein argues, is the "threat environment" of an occupied territory, and that this must be explored from the perspective of both the occupier and the occupied population [@edelstein_occupational_2008]. Edelstein argues that the populations of occupied territories "determine their external threat environment by assessing the relative threat posed by the occupying power as opposed to other third-party states," and importantly, that such a judgment rendered by the occupied population is not static, but one that can change, largely as a result of the type of strategy employed by the occupying power [@edelstein_occupational_2008]. 

Edelstein further argues that the occupying power's strategies are either "cooperative or coercive" in nature, and that there are three general forms, consisting of "accommodation, inducement, and coercion" [@edelstein_occupational_2008]. A strategy of accommodation refers to an occupying power attempting to placate the occupied country, typically by "co-opting local elites into the occupation project" [@edelstein_occupational_2008]. A strategy of inducement, on the other hand, seeks to win over the occupied population by "providing resources...and improving the welfare of the local population" [@edelstein_occupational_2008]. Finally, a strategy of coercion is "the actual or threatened use of force to defeat elements of the population that resist or threaten to resist an occupation" [@edelstein_occupational_2008]. With respect to the occupations of southern and northern Korea, Edelstein argues that both the Soviet and American occupation forces implemented a strategy of coercion, but that the Soviets were more successful at doing so than the Americans were [@edelstein_occupational_2008]. 

# The Principal-Agent Approach

I argue that a principal-agent approach is relevant and insightful for the study of military occupations. Long used in economics, management, as well as in political science, the principal agent model explores problems of agency, or how a principal (as a superior or boss) ensures that an agent (as a subordinate or employee) does what it is supposed to do. That is, principal-agent models examine and explore how principals ensure that an agent acts in accordance with the will and in pursuit of the goals of the principal. Though previously not applied to the specific topic of military occupations, principal-agent models have been used to explore the features of civil-military relations [@feaver_armed_2003], the arming of indigenous military forces by interventionist states [@rittinger_arming_2017], inherent problems in fighting counterinsurgencies [@byman_friends_2006], and issues that arise in coalition governments [@thies_keeping_2001]. In this paper, I will borrow some important aspects of the principal-agent model and argue for their  application in settings of military occupation.  

In any principal-agent setting, there exists some form of both "strategic interaction and hierarchy"[@feaver_armed_2003]. Scholars have explored the various ways in which principals embark on schemes to monitor and manage agents, and the ways in which agents may avoid carrying out the work that principals have hired them to do [@gates_working_1997]. For example, Michael Thies argues that some of the control mechanisms that coalition governments use to manage diverse delegations include the selection of agents whose beliefs are in alignment with those of the principals; the construction of contracts or other agreements that spell out the roles and responsibilities between principal and agent; in some cases, the requirement of agents to request approval from the principal before taking certain actions; and restricting the ability of an agent to act by "delegating responsibility jointly to two or more agents, each with different interests" [@thies_keeping_2001]. Scholars have also used a principal-agent approach to describe how, for instance, democratic societies function as principals when hiring elected leaders as agents through the use of elections to represent the interests of voters. Additionally, agency theory has been used to describe the circumstances under which principals may decide to take actions to remove agents, such as through removal from office [see @downs_conflict_1994].

In short, a principal-agent model can be used to describe multiple types of relationships that exist in business as well as within domestic and international politics. The key problem is recognition that an effective principal-agent relationship is not a guaranteed nor automatic outcome. Rather, principal-agent relationships must be managed effectively. When a principal-agent relationship is managed effectively, the principal can confidently be assured that the agent will generally act in accordance with the principal's interests. When it is not, the principal lacks confidence in the agent to act in accordance with its goals, and the agent seeks to subvert the principal. Let us now explore how principal-agent approaches are relevant in the setting of military occupations, and specifically, which aspects of the principal-agent approach are especially helpful in explaining the divergent occupation outcomes with respect to the Soviet Union and the United States in Korea.  

# A Multi-layered Principal Agent Approach to Military Occupation

In the context of military occupations, I argue that there are at least four layers of principal-agent relationships at work. The first two layers occur prior to the formation of a recognized and autonomous government in the occupied territory, while the third and fourth layers are relevant after official recognition of this government occurs. In this first layer, the focus is on the relationship between the patron state (principal) and the occupying force, usually a military commander (agent). An example would include President Harry Truman and General Douglas MacArthur in Japan, or President George W. Bush and L. Paul Bremer as the head of the Coalition Provisional Authority (CPA) following the US invasion of Iraq in 2003. The issues surrounding this "first layer" of principal-agent relationships are significant. Questions such as "does the patron state have a strategy for military occupation?", "has the principal chosen a well qualified and skilled agent to lead the occupation?" are important considerations in this "first layer" of principal-agent considerations of military occupations.^[ With respect to the American military institution in particular, principal-agent issues abound all of the time, not just during military occupations. These are examined in great detail in Peter Feaver's _Armed Servants: Agency, Oversight, and Civil-Military Relations._ 
]

The focus of my paper, and the crux of my argument, focuses however on a "second layer" of principal-agent relationships that is also relevant whenever a military occupation occurs. In this "second layer," the occupation force serves as the principal while the rising, fledgling government - which is in the process of forming - of the occupied territory serves as the agent. It is this second layer of principal-agent relationships that I focus my attention on in this paper. Additionally, note that this framework also presents an interesting theoretical insight in that the occupying commander or representative simultaneously serves as the agent in the first layer of the relationship but as principal in the second layer.^[
Though principal-agent frameworks are not explicitly examined, an excellent book on the topic of American proconsular leadership is Carnes Lord's _Proconsuls: Delegated Political-Military Leadership from Rome to America Today_[see @lord_proconsuls_2012].

Though I do not address the theoretical insights at depth in this paper, my theory posits that a third and fourth layer of principal-agent issues arise in situations in which, as a result of military occupation, a sovereign state is formed. In the event that the occupying force remains in the country, it can be said that its efforts now constitute that of an advisory or assisting role (as opposed to an occupation role), as seen in layers three and four of table 1. Because the state in which it previously occupied is now sovereign, in many respects, the roles have been reversed from those in layer two: the advisory force is now to some degree the agent of the client state (layer four). This switch in roles occurs because the formerly-fledgling government, now sovereign, is embodied with legitimate authority, and as such, it can to a greater degree establish "rules" which govern the behavior of the advisory force. However, as layer three shows, the advisory force is nonetheless still the agent of its patron state, and in that respect, will still first and foremost act in accordance with the patron state's wishes. The point of contrasting layers one and two with layers three and four is to highlight that with respect to military occupations, the occupation force has distinct "principal" roles in layer two which are no longer present, at least not to the same degree, after a fledgling government in an occupied country, is officially formed. What are these important roles of an occupying force in layer two?

\begin{table}[ht]
\caption{Multi-Layer Principal Agent Models in Military Occupations} % title of Table
\centering % used for centering table
\begin{tabular}{c c c} % centered columns (3 columns)
\hline\hline %inserts double horizontal lines
Layer & Principal & Agent   \\ [0.5ex] % inserts table heading
\hline % inserts single horizontal line
1 & Patron State & Occupying Force \\ % inserting body of the table
2 & Occupying Force & Fledgling Leadership of Occupied Territory  \\
\hline\hline %inserts double horizontal lines
3 & Patron State & Advisory Force \\ % inserting body of the table
4 & Client State & Advisory Force  \\
[1ex] % [1ex] adds vertical space
\hline %inserts single line
\end{tabular}
\label{table:defecttworounds} % is used to refer this table in the text
\end{table}

Because initial military occupations are often marked by great uncertainty, the occupation force commander (principal) must often make decisions with little information, guidance, or resources. Indeed, the occupation force (principal) encounters: issues related to "selection," that is, choosing the local leaders (agents) with whom to begin a relationship with, in hopes that it will yield a fruitful relationship and potentially, a future government; problems of "delegation," that is, the principal must decide which tasks or agenda items will be accomplished by the agent in pursuit of the principal's interests and which tasks will reside with the principal; and finally, problems of "monitoring and compliance," that is, the principal must determine how it will ensure that the agent is in fact doing what it is supposed to do. These important components of the principal-agent framework: selection, delegation, and monitoring/compliance are interactive, and I argue especially so, in the context of a military occupation. An occupation force may select leaders with whom it is possible to work together, but if delegation and compliance efforts are bungled or mismanaged, negative consequences can occur. Similarly, one can adeptly delegate and impose a compliance scheme of sorts, but if the leaders with whom one works are flawed in major ways, such as they are viewed by the local populace as illegitimate, then similarly, negative results can occur that impact the military occupation. 

I argue that with respect to the second layer of principal-agent relationships, the Soviet occupiers were able to more successfully manage their agents, the Koreans in the North, than the American occupiers were able to manage their relationship with their agents, the Koreans in the South. Understanding the decisions and consequences made by each occupation force with respect to  selection of agents, as well as delegation to, monitoring of, and compliance of these agents, reveals a drastically different story unfolding in the north of Korea than in the south. After exploring these issues in depth - selection, and then delegation, monitoring, and compliance - I will examine the relationship that existed between the occupation force and the chief agent. Ultimately, the Soviet relationship with Kim Il Sung was far more effective than the American relationship with Syngman Rhee in the years 1945-1948, emphasizing the degree to which the Soviets managed their principal-agent relationship better than the Americans did. As a result, the Soviet military occupation was relatively more successful than that of the Americans, at least in the short run.  

# Important Historical Background

Before he died, President Franklin D. Roosevelt had envisioned a "trusteeship" of Korea whereby several of the Great Powers, most notably the United States and the Soviet Union, would guide nations that had long been colonized towards independence [@cumings_origins_1981]. These decisions had been discussed between Stalin and Roosevelt at the Tehran and Yalta conferences in 1943 and 1945, respectively, but Korea itself had never been the primary focus of these meetings. Additionally, the great powers had not formulated a clear vision for what a trusteeship would practically involve with respect to the great powers working together [@lee_soviet_1991]. 

After the United States dropped the first atomic bomb on Hiroshima on August 6, 1945, the Soviets declared war on Japan on August 9 [@lee_soviet_1991]. Requiring only a moderate amount of preparation, Soviet military forces were poised to expel the Japanese from Manchuria and to enter the northern part of Korea. Soviet military forces encountered relatively little resistance from the Japanese inside of Korea and reached the 38th parallel - which had been agreed upon by both sides somewhat surprisingly as a result of recommendations made by US Army Colonels C.H. Bonesteel and Dean Rusk - in the first week of September, 1945 [@lee_soviet_1991]. 

With respect to the American context in Korea, it is generally understood that following the use of the atomic bomb on Japan, first on Hiroshima and then on Nagasaki, the Japanese surrendered faster than what many American leaders thought [@lee_soviet_1991]. Unlike the Soviets, which fought overland into Korea, albeit with far less casualties than had been sustained at other battlefields during World War Two, the Americans did not fight into Korea. The XIVth Corps, which had previously fought at Okinawa, was located approximately 600 miles away, and General Douglas MacArthur, who was focused on planning the upcoming American occupation of Japan, tapped the XIVth Corps Commander, to lead the occupation of American forces of Korea south of the 38th parallel. MacArthur officially notified Hodge on August 15, 1945, and set a target date for occupation of September 8 [@kang_united_1970]. 

What did each power hope to achieve in Korea at the outset of their respective occupations? Understanding the goals and interests of the Soviet Union and the United States can help inform why the occupiers made their respective selection decisions. According to the majority of historical sources, the Soviets viewed Korea  through predominantly a security lens, especially early in the occupation, and thus, the major goal in Korea was to ensure the existence of a "buffer state" in which no power could attack the Soviet Union through Korea [@lee_soviet_1991]. Additionally, Soviet control of several strategic regions in northern Korea, which included access to ports, would ensure Soviet access to both the Yellow Sea and the Sea of Japan [@hak_paik_soviet_1995]. In this sense, self-interest loomed large in the minds of the Soviets. The American goals in Korea, on the other hand, underwent an extensive evolution in a short amount of time. Initially, the US goals in Korea focused on the operational and tactical goals, but these goals would become far more grandiose as the relationship between the United States and the Soviet Union changed in the period after World War Two, especially as America's policy of containment further developed [@chay_unequal_2002].

# Decisions of Selection With Respect to Japanese Colonialism

In terms of the principal-agent framework, selection issues confronted both occupiers from the start of their occupations. Perhaps the most significant decision was if and to what degree to dismantle the existing Japanese colonial administration, which had been in place since 1910. The Soviets decided to completely dismantle any and all vestiges of Japanese authority, whereas the Americans took a different approach, at least early on, determining that working through Japanese authorities offered short term benefits that would many of the most immediate tasks. This crucial distinction in selection - to work through Japanese agents by the Americans, and not to for the Soviets - would have significant repercussions for both sides. General Matthew Ridgeway, who later commanded all forces during the Korean War, states in his memoirs that the early decision of selection (to work through the Japanese after occupation) "cost [the United States] the confidence and cooperation of the Korean people" [@ridgway_korean_1986]. 

Most historical sources indicate that as the Soviet Union was more intently focused on forming outcomes in Eastern Europe, they were not as rigid in their concerns for the internal politics of Korea. It is true that the Soviets certainly wanted a regime that would be favorable to Moscow, but not necessarily one that followed every dictum of Soviet policy [@armstrong_north_2013]. Thus, it appears as though the Soviets were willing to allow the Koreans to possess a higher degree of autonomy that they did not allow the regimes they were attempting to establish in Eastern Europe[@lee_soviet_1991]. Instead, the main goal of the Soviets in Korea was to ensure that no one power could control Korea that was hostile to Moscow's interests [@hak_paik_soviet_1995]. When the Soviet Commander of occupation forces in Korea, Colonel-General Ivan Chistiakov, arrived at the Pyongyang Airport in September of 1945, he issued the following proclamation upon his arrival in Pyongyang in September 1945: "Koreans! The Soviet Army and the army of the Allies drove the Japanese plunderers out of Korea. Korea became a free nation...Recollect the bitter period of time under Japanese rule" [@kim_political_1999]. Stalin likewise provided guidance later in October 1945 to the Soviet Far East Commander, General A.M. Vasilevskii, instructing him not to obstruct the formation of "anti-Japanese democratic organizations and parties" [@lee_soviet_1991]. 

In the north, the early decision by the Soviets to do away with the old Japanese order began to usher in a sense of something new and different. Were the Soviets actually trying to establish a satellite state in North Korea?  Most scholars believe that the answer to this question is no, at least initially. For evidence, one must consider the behavior of the Soviet occupiers in the early days after arriving in Korea. The Soviet Army had a severe problem of controlling its forces in the early weeks of the occupation, as many of its soldiers engaged in pillaging and raping, to the point that Stalin personally addressed the issue in correspondence to the military command [@lee_soviet_1991]. By by renouncing the former Japanese colonialists, the Soviets nonetheless created an environment which fostered the growth of predominantly left-wing, anti-conservative political organs. It is further important to note that most historians acknowledge that these bodies, while they may have favored liberal policies, were not initially filled with communists. In fact, compared to Eastern Europe, there were relatively fewer and less-experienced communists in Korea at the time of the Soviet occupation [@ree_socialism_1989]. However, these bodies nonetheless would incrementally become favorable to the Soviets as the Soviet occupiers helped implement liberal policies and empower the local Koreans to exercise local authority to exercise local authority [@ree_socialism_1989]. 

The American approach to the Japanese legacy in Korea was markedly different than that of the Soviet Union's, and for reasons which, once unpacked, are somewhat understandable and straight forward. Like that of the Soviet Union's, American strategic goals in Korea at the outset of the occupation were somewhat ill-defined. Historians argue about exactly when Truman's strategic policy of containment began to be exercised in Korea [for example, see @chay_unequal_2002], and how containment as a policy ever could have been in harmony with the loose vision of a "trusteeship" as had been agreed upon in the major conferences prior to the end of World War Two. 

In the early months of the occupation, the selection decisions of American occupation forces generated significant resentment and anger among large portions of the Korean people. The most consequential selection decision by the Americans was that of retaining and working through many of the Japanese administrators, who possessed intimate local knowledge and logistics skills that would greatly assist the Americans in facilitating the departure of more than 122,000 Japanese troops located in the southern zone of Korea (roughly 70,000 Japanese were in the Soviet Zone at the time of occupation) [@kang_united_1970]. The mission to return the Japanese from Korea occurred roughly between September 1945 - December 1945. During this critical four month period, the American occupation force actually succeeded remarkably in the narrowest of its missions, the removal of Japanese forces from Korea (all but 500 of the Japanese had left Korea out of the 122,000) [@kang_united_1970]. One can understand why such a decision was made: in the short term, Lieutenant General Hodge, the commander of American occupation forces and the XIVth Corps, understood his first and primary mission to be ensuring the orderly surrender of the Japanese and their departure from Korea [@kang_united_1970]. 

However, the decision to work through the Japanese administrators was the beginning of an overall theme of selection that would hold significantly longer-lasting consequences for Korea in the south. In addition to seeking help from Japanese colonial administrators, the Americans were highly suspicious of what they perceived to be anything resembling radical Korean politics, mainly out of fear that these radical elements were Soviet-inspired or sympathetic to communism [@cumings_origins_1981]. Thus, as a result, the American occupation forces were highly dismissive of virtually all Korean political entities that were confirmed or perceived to be connected with left-wing policies, and alternately very favorable towards the conservative, right-wing Korean political class [@cumings_origins_1981]. 

Even before the arrival of US forces, Koreans had already started to take collective action in order to best posture themselves for achieving independence. They were indeed excited about the prospect for achieving independence after 35 years of Japanese colonialism. The Koreans formed the Committee for the Preparation of Korean Independence (CPKI) as a way of leaning towards the notion of independence. But the Americans rejected the CPKI on the grounds that the policies it promoted were too liberal, and soon afterward rejected another pro-independence entity, the People's Republic of Korea (KPR), which had been established by the moderate Korean politician, Yo Un-hyong [@oh_us_2002].

But the Americans were not yet ready to grant independence to Korea, and selecting the conservative, right-leaning political class made for a more expedient solution to immediate American problems. A majority of the conservative Koreans spoke English, making cooperation with the American occupation forces easier in a practical sense [@cumings_origins_1981]. Additionally, there is strong evidence that once chosen as the initial agents, the conservative Korean political class further colored the anti-liberal perceptions that the Americans had adopted upon their arrival to Korea [@cumings_origins_1981]. Finally, one must recognize that in the absence of any other key guidance from Washington, Lieutenant General Hodge and key members of his staff were concerned about maintaining a strong anti-communist stance in Korea, especially amid a backdrop of simultaneous Soviet occupation in the north [@matray_reluctant_1977]. However, in selecting as its agents the conservative, nationalist Koreans, the Americans facilitated internal divisions in Korean politics that caused significant resentment, anger, and frustration among the Korean population. Moreover, in the months to come, the rightists would become stronger and gain momentum, and actively thwart many of the developing goals that the Americans deemed essential for success of their occupation.  

One can detect an immediate difference in the characteristics and attributes of the agents selected by each respective principal. The Soviets chose to abandon legacy Japanese administrators, and instead to ally with moderate and left-wing political classes in the north. The Americans on the other hand, chose to work through the Japanese colonial system initially, and simultaneously favored right-wing, conservative nationalists. These early selection themes would only grow deeper in each respective occupation zone. 

# Delegation, Monitoring, and Compliance

Concurrent with choices of selection, each occupying power, as principal, made decisions involving issues of delegation, monitoring, and compliance with respect to their agent. These decisions, as in the decision to choose an initial agent, varied widely between the Soviet Union and the United States, resulting in vastly different trajectories in northern and southern Korea. The Soviets implemented a scheme whereby the occupying power would empower the agent but be in a position to strongly influence the agent's choices. George McCune described the Soviet scheme as an approach that was "inauspicious but firm" [@mccune_korea_1950]. The Americans, on the other hand, struggled to devise an effective delegation, monitoring, and compliance scheme altogether, largely stemming from selection issues described above. The selection of Korean conservatives ensured against the establishment of communism in the south, but as a consequence, their selection also significantly impacted the formation of a conducive political environment. As a result, a unified, Soviet-leaning government began to emerge in the north of Korea, whereas in the south, the Korean political picture was marked by rampant infighting, disunity, and dysfunction. So to determine the degree of effectiveness of each principal's delegation, monitoring, and compliance scheme, we must examine the political environment fostered in each occupation zone, and analyze the principal's decisions with respect to fostering these environments. 

It is first vital to understand how the strategic picture unfolded in late 1945-1946 with respect to Korea. The Americans and Soviets attempted to further elucidate a path of trusteeship during a conference in Moscow in December, 1945 (which came to be known as the Moscow Conference). The American and Soviet delegations hoped to clarify a path towards trusteeship, but the delegation ultimately failed. At issue was the very concept of trusteeship itself. The conservative, rightist-leaning Koreans adamantly opposed trusteeship on the grounds that trusteeship delayed Korean independence, and the Soviets were able to convince their Korean agents that trusteeship would ultimately prove good for them - a task that was made increasingly easy by the fact that the Soviet agents in the North became increasingly pro-communist and aligned with the Soviet Union [@mccune_korea_1950; @hak_paik_soviet_1995; @kim_political_1999; @kang_united_1970]. The Moscow Conference did agree, however, to revisit trusteeship at a later date in 1946 - what would later be known as the Joint Commission - but this too would fail, first in 1946 and later in 1947 [@mccune_korea_1950; @kim_political_1999].

## The Soviets in North Korea - Influence from Behind

The Soviet scheme of delegation, monitoring, and compliance involved empowering local Koreans while heavily shaping outcomes from behind the scenes. As such, the Soviets were able to influence results in northern Korea to their liking but in a manner that built the machinery of north Korean governance with a north Korean flavor. Additionally, the Soviets were able to find and empower their chief agent, Kim Il Sung, from a relatively early time in the occupation and, importantly, to foster a relationship that was mutually beneficial and effective.  

The most significant way in which the Soviets influenced the development of the North Korean political system was in instituting the Soviet Civil Administration (SCA) in October, 1945. The SCA was led by General Terentii Shtykov, a Soviet military officer with extensive civil-political training, who would go on to become the Soviet Union's first ambassador to the Democratic People's Republic of Korea [@lee_soviet_1991]. It is notable that the Soviets chose an officer from outside of the military command to lead the political apparatus of the SCA, for it demonstrates that the Soviets not only prized political formation, but that they understood the process required a deliberate effort that was separate from the security tasks of occupation. 

Importantly, the structure of the SCA reflected the very structure of the local Korean government present in the North - the North Korean People's Political Committee (NKPPC) [@lee_soviet_1991]. There were ten departments of NKPPC, covering areas such as agriculture, justice, health, press, and industry [@ree_socialism_1989]. Under Shtykov, each of the SCA's bureaus was led by a senior Soviet political-military officer whose mission was to advise his respective bureau of the NKPCC [@lee_soviet_1991]. Moreover, the Soviet influence into Korean political affairs trickled further down into the provincial levels, where Soviet advisors were present to help steer, guide, and monitor the actions of local people's committees [@cumings_origins_1981; @lee_soviet_1991]. And yet at the same time, these advisors and the overall SCA behaved in such a manner so as to empower the Koreans as opposed to direct them forcefully. This of course was easier given that these Koreans in positions of influence were generally left-wing and moderates, but still, the tone of the Soviet manner of influencing is worthy of notice. 

Thus, in the period October 1945-February 1946, the SCA significantly influenced the direction of north Korean politics. By establishing an apparatus that provided access as well as influence, a Soviet voice was present in the decisions that the People's Political Committee and their subordinate political committees made and implemented. By essentially "manipulating" the People's Political Committees, the SCA ensured that Soviet guidance and direction was present as multiple changing reforms were instituted regarding land policy, the economy, and numerous other issues [@lee_soviet_1991; @lankov_stalin_2002]. 

Perhaps most importantly, the SCA helped to cultivate a political environment such that northern Korea increasingly developed into a repressive state conducive to Soviet goals and interests. The machination of the SCA was aided by several hundred influential Soviet Koreans, whose common language with the Soviet occupiers enabled the Soviet Koreans - many of them communists - to further influence the local people's committees [@lee_soviet_1991]. Additionally, the Soviets aided the North Koreans under Kim Il Sung as early as October 1945 to gain and maintain control of the police apparatus in northern Korea [@kim_political_1999]. Wielding control of the police state, Kim appointed his trusted lieutenants to top police and intelligence posts, which further solidified his control and Soviet influence into a growing police state  [@kim_political_1999]. In the years to follow, the police forces would evolve and change, as would Kim's hold on paramilitary and ultimately, military power in North Korea [@kim_political_1999; @lee_soviet_1991]. All of this was done under the watchful assistance and guidance from the Soviet authorities. In so doing, the Soviets avoided the perception of directing a revolution, yet for all intents and purposes, they fostered and guided North Korea into a pro-Soviet state that was capable of maintaining power on its own.  

## The US Military Government in South Korea - Disjointed with Washington and Unable to Get Ahead

The US Military Government in Korea (USMGIK), favoring the conservative, right-leaning Koreans largely out of fear of the potential of a rise from the left, instituted a delegation and monitoring scheme that was flawed in its very design and thus, ineffective. Many of these flaws arose from errors made in the selection decisions of the American occupation to empower the Korean right, but these flaws were compounded by a rather obvious disunity between USMGIK and planners in Washington, and as a result, the Americans failed to establish an effective delegation and monitoring scheme between themselves and their agents. Critically, in the first 120 days of the occupation, the empowering of the right meant that conservative Koreans were chosen to fill key positions within the branches of the Military Government, notably in police and security roles [@kang_united_1970]. However, this also resulted in non-rightist voices becoming excluded from participation, and as a result, these moderate and leftist voices in the south joined together against both the Koreans on the right and the American occupiers [@kang_united_1970]. 

The Americans realized that Korean politics were becoming polarized, and actually took action to try and rectify this unfolding dynamic. For example, USMGIK formed an "Advisory Council" in an effort to bring in different Korean voices to influence Hodge and the Military Government. However, out of the 11 members chosen, nine were distinctly of a conservative background, and thus, the advice and recommendations that the Americans received from their Korean agents was heavily skewed [@cumings_origins_1981]. 

Cumings also points out that perhaps worse than deciding to work through Japanese colonial administrators in the early days of the occupation was the choice made by the Americans to retain the actual structure of the Japanese colonial bureaucracy itself [@cumings_origins_1981]. Cumings points out that in essence, the very same functions and features of the Japanese colonial regime were now performed by Koreans of one political class - the conservative nationalists - which served to elevate a political class at the expense of others and to infuriate the majority of local Koreans [@cumings_origins_1981]. Of perhaps all of the different bureaucracies where this feature existed, none was perhaps more important than in the police [@cumings_origins_1981]. Like its counterpart in the north, the police apparatus in the south of Korea would repress alternate political viewpoints, censor the press, and otherwise ensure that its own political ambitions materialized [@cumings_origins_1981]. 

However, the key difference between what was occurring in the north under the Soviets and in the south under the Americans is that the Americans did not desire the political polarization that was unfolding. Instead, it appears as though the Americans were indeed powerless to form a truly effective delegation and monitoring scheme given the selection decisions it had previously made. My argument here is that while these selection decisions made by Hodge ensured that such political division would occur, but it is also true that Hodge could see what was unfolding and was increasingly concerned. In fact, as early as late 1945 - just a few months into the occupation - Hodge and the Americans were not optimistic about the trajectory of Korea. Hodge informed his superior, General Douglas MacArthur, who forwarded Hodge's concerns to Washington D.C. and to President Truman, that the situation in Korea was deteriorating and unlikely to result in a desirable political outcome. Indeed, Hodge warned:  

\singlespacing

>  **In South Korea the US is blamed for the partition and [there] is growing resentment against all Americans in the area including passive resistance to constructive efforts we make here...The Koreans want their independence more than anything and want it now. This stems from the Allied promise of freedom and independence which is well known by every Korean without the qualifying phrase "in due course."...In summary, the U.S. occupation of Korea under present conditions and policies is surely drifting to the edge of a political-economic abyss from which it can never be retrieved with any credit to United States prestige in the Far East** [Hodge in @lawler_foreign_1969].

\doublespacing

The timing of Hodge's concerns is important, as it occurred before the Moscow Conference. Hodge earnestly tried to persuade his own government of the pitfalls of trusteeship, and he specifically warned the State Department about explicit use of the word "trusteeship."^[
In a telegram to MacArthur, which was forwarded to Washington D.C., Hodge warned that "trusteeship hangs over them as a sword of Damocles. If it is imposed now or at any future time it is believed possible that the Korean people will actually and physically revolt." [@lawler_foreign_1969]
] Three days had transpired after the Moscow Conference when Hodge learned - through the press - that the Soviet and American diplomats had agreed to a future commission to further discuss plans for trusteeship and the future of Korea, and Hodge had little time and choice but to react as best as he could to a firestorm of public outrage [@cha_search_1986]. Still, President Truman and the State Department doubled down on its commitment to Korea, stating that "the United States will intensify its efforts to create a self-governing and democratic Korea neither subservient to nor menacing to any power" [Harry Truman in @kang_united_1970]. Secretary of State Byrnes, who later resigned as a result of Truman's frustration with him, favored trusteeship very strongly, largely out of a desire to maintain and stick to the major plans decided late in World War Two [@cha_search_1986].^[
Many of the sources I reviewed indicated Hodge's frustration with US Department of State officials who were in the Military Government in Korea. As is often the case, at least in the author's personal experience, the military commanders and the diplomats share differing assessments and goals. Issues of command and control - and who is overall in charge - is always a thorny issue, especially in overseas occupation/advisory efforts.]
In the months that followed, the Joint Commission - recommended by the diplomats who had met in Moscow as a follow-up meeting to further discuss the future of Korea - also failed, prolonging the open-ended question about Korea's future.   

With desperation, Hodge and USMGIK attempted to form yet again a political entity that would represent the broader factions of southern Korea. In July of 1946, Hodge announced the formation of an Interim Legislative Assembly and targeted the 15th of September as its beginning [@kang_united_1970]. USMGIK also implemented steps to help make the Interim Legislative Assembly more appealing to Koreans who had up until this point been excluded from participation in Korean politics. For example, the American Military Governor, Andrew Lerch, withdrew a previous USMGIK ordinance that had declared some "82 acts considered [to be] offenses against the military government" [@kang_united_1970]. Additionally, USMGIK conducted extensive public opinion polling at around this same time, asking the Koreans about what type of government they would prefer to have in place [@kang_united_1970]. Two points from these public opinion polls are noteworthy. First, 85% of all respondents selected their preference for the rule "of all the people through a representative government" as opposed to "rule by one" [@kang_united_1970]. Second, and more striking, is that the respondents ranked their preference for the form of government along the following lines: 13% favored capitalism, 70% favored socialism, 10% favored communism, and 7% indicated that they do not know [@kang_united_1970]. These efforts demonstrate that the Americans truly desired to affect the political situation in Korea towards what they thought were desirable ends, and that they had noticed that the previous nine months of occupation, combined with the impasse of the Joint Commission, had only reinforced the difficulties of the situation. 

Yet American efforts to foster a more-conducive political environment would came up short again.  The very agents whom the Americans had initially selected the previous year actively undermined the major goal of their principals. Initial election procedures were complicated, eliciting cries of unfairness from the Koreans, and Hodge subsequently appointed nearly half of the legislative assembly's members, many of whom were not ardent rightists, drawing strong criticism from the conservatives [@kang_united_1970]. The assembly did end up forming, but in facing what appeared to be an impossible situation, Hodge could not persuade important moderates to fill seats, nor prevent strong criticism from both the extreme right and the extreme left. In the end, 55 of the 85 seated members would end up being strong rightists [@kang_united_1970]. In the process, though, the degree to which the Korean right trusted Hodge dropped to such a low level that it would never recover. In essence, an effective and well-managed delegation, monitoring, and compliance scheme - in the form of a conducive political environment - never truly materialized between the Americans and the Koreans in the south despite multiple US attempts to create one. 

# The Principal and the "Chief" Agent

The final examination of the principal-agent relationship managed by the Soviets and the Americans in northern and southern Korea must involve the specific relationship between the respective occupation authorities and their chief agent. Are there characteristics that are noteworthy of comparison and contrast between Kim Il Sung and the Soviet occupation authorities and between the USMGIK leadership and Syngman Rhee?  What behaviors or actions on both the principal and agent's part are instructive here that are indicative of the broader principal-agent relationship, and can we tell the degree to which this may have impacted the overall result of each occupation? 

## Kim - The Right Man at the Right Time in the North

Kim returned to Korea in 1945 after several years of fighting the Japanese as a member of the Soviet Army himself, and thus, he had a proven record of loyalty to the Soviet political and military machine [@lee_soviet_1991]. However, Kim was not the first choice of the Soviet occupation regime to carry the mantle of leadership for the Koreans in the Soviet Zone. The Soviets first tried to solicit the help and involvement of Cho Man-Sik, a popular nationalist leader who commanded significant popular support. But Man-Sik proved too headstrong in his nationalist desires for Soviet likings, and therefore, the Soviets deemed him insufficiently moldable to the purposes of the Soviets in creating a pro-Soviet state [@lankov_stalin_2002]. Kim, on the other hand, possessed all of the right qualities that the Soviets were interested in: a pro-Soviet leaning leader, who was popular among the Koreans, and who was interested in a continuing relationship with the Soviet state. 

Kim also possessed tremendous political skills. In the early months of the occupation, he managed to adeptly maneuver himself into key leadership roles of the burgeoning Korean political institutions in the north. In the Spring of 1946, Kim became the head of the North Korean Communist Party, and later that year, with General Shytkov's blessing, traveled to meet with Stalin in Moscow, where discussions unfolded on how to continue uniting leftist parties in North Korea [@lankov_stalin_2002].^[
One source I reviewed (Lankov, 2002) had an extensive footnote in which a claim was made that Kim had been sent to Moscow to meet Stalin and to secure his approval as de facto leader of the Soviet zone in Korea as early as September, 1945. However, Lankov questions the validity of this report, as do I, largely for the reason that most of the sources that I encountered in researching this paper portray the early weeks of Soviet occupation as rather chaotic and unplanned, rather than a well thought-out and pre-planned operation. The author acknowledges that he did not find a conclusive answer as to whether this meeting between Kim and Stalin actually took place. ] As the "democratic reforms" unfolded in North Korea, chief of which was the redistribution of land, Kim had a central role to play, either at or near the very center of action [@armstrong_north_2013].. 

Guided by the Soviets, but also given ample room to operate, Kim gradually increased his hold on power and emerged as the chief agent, and thus the leader of what would become North Korea in 1948. Throughout this time, the Soviets certainly stayed involved and heavily advised Kim, but the degree to which they had to micro-manage or force their will onto Kim seems minimal. Rather, Kim agreed with the overall direction and goals of the Soviets in making a pro-Soviet state in northern Korea, which further strengthened the ties between the Soviet occupation authorities and Kim. Within Korea itself, Kim's pro-Soviet and pro-communist bent ensured that as the trusteeship question continued to flare, he would emerge at the top of the political scene, while other nationalists, who up until that point had been popular among the population, were removed [@lankov_stalin_2002].^[
According to Lankov, Cho Man-Sik, whom the Soviets initially tried to court in 1945, was thrown in prison and likely, summarily executed by fellow Koreans in 1950 at the outset of the Korean War. This same fate likely met other nationalists as Kim continued to increase his hold on power.
] Simultaneously, one must acknowledge the political skill that Kim wielded to achieve supremacy in North Korea. He understood how to harness public opinion and steer public support towards himself by appealing to powerful Korean cultural symbols, such as the family, helping to develop a strong and powerful cult of the personality [@armstrong_north_2013]. 

In terms of the second layer of the principal principal-agent relationship, the important thing to emphasize here is that the Soviets had found someone who aligned with their goals in Kim Il Sung, and that as a result, felt comfortable in empowering him to achieve their vision for North Korea. Kim was popular among the population, skilled politically, and loyal to and therefore receptive to Soviet guidance. This is very different from what can be said about what occurred in the south between the Americans and Syngman Rhee.   

## Rhee - America's Only Option?

As Syngman Rhee grew in power, he and Hodge's relationship deteriorated. This is especially evident in the manner in which Rhee would often court other US actors outside of Hodge in an attempt to exert his influence. If receptiveness and guidance characterized the relationship between Kim and the Soviets in the north, then distrust and disdain would be appropriate in describing the relationship between Rhee and Hodge in the south. Hodge never fully recovered in terms of Korean public opinion following the decision of the Moscow Conference to postpone the notion of trusteeship and, later, the failure of the Joint Commission (first in 1946, and again in 1947). But one of the reasons Hodge and USMGIK never recovered is because Rhee actively worked against them by inciting the press to denounce USMGIK efforts [@kang_united_1970; @cha_search_1986]. 

Moreover, in early 1946, as USMGIK developed a plan for forming SKILA, a wedge between the State Department and Hodge also began to form. The State Department felt that working with the Soviet Union to forge a Korean solution was not only preferred but still possible, whereas Hodge had, by this point in time, adopted the view that if permanent American and Soviet zones were to endure, the United States would never be able to realize its goal of creating a "unified, independent, and democratic" Korea [@cha_search_1986]. After several months of leading American efforts on the ground, Hodge had attenuated his hopes for Korea with what he believed to be Korean political realities. By this point, Rhee stood atop the Korean political scene. He and the conservatives had won the majority of seats in the SKILA, and they also held key posts within the Military Government. 
Rhee's efforts to manipulate public opinion against USMGIK and the American occupation were not confined to Korea. Rhee traveled to Washington on an extensive trip from December 2, 1946 to April 21, 1947 in an effort to deliberately persuade the US Congress about the future of Korea. Relying on several contacts in Washington to help him gain access to members of the 80th Congress, Rhee took this opportunity to argue his case for what he desperately wanted: the establishment of a separate South Korean state that would enjoy significant US support without the interference of a US Military Government [@cha_search_1986].^[
Rhee had spent considerable time in the United States previously, having earned a PhD from Princeton University, and he also spoke fluent English [@cha_search_1986]. 
]  

Hodge, however, also traveled to Washington at roughly the same time, having been called back to Washington to report on the situation in Korea to Truman and to Congress [@cha_search_1986]. Hodge told a Senate Armed Services Committee (SASC) hearing that the situation in Korea was indeed fragile. Hodge presciently warned the SASC of the dangers to follow should the Americans withdraw, pointing to a strong and well-supplied North Korean Army [@cha_search_1986]. In Hodge's estimation, Washington needed to work with Moscow to push some sort of negotiated settlement, and not an ambiguous trusteeship [@cha_search_1986]. Indeed, Hodge's comments reveal the difficult policy choices facing Washington at the time. Should Washington extend the military occupation indefinitely, it would face extremely difficult challenges. Should the Americans withdraw, American credibility in Asia would suffer, and the risk of war would greatly increase [@cha_search_1986].

When Rhee and Hodge returned to Korea in April of 1947, the relationship between the two men was all but broken. Rhee continued to undermine the Military Government by inciting public opinion against the Americans and portraying Hodge as intrinsically connected to the notion of trusteeship, a claim which was simply untrue [@cha_search_1986]. Hodge continued to obey his orders, much as he did not particularly agree with staying the course, even as the Americans and the Soviets attempted to reignite the Joint Commission one final time in the Spring and Summer of 1947. Unsurprisingly, these efforts once again failed. The Soviets insisted on blocking any groups which had previously opposed the concept of trusteeship - which in essence meant blocking Rhee and other nationalists and paving the way for a communist-leftist government for Korea - and the Americans refused to acquiesce to this demand [@cha_search_1986]. 

The combination of Rhee's astute political skills in further manipulating Korean public opinion against USMGIK and the genuine mistakes made by Hodge and American leaders in the early months of the occupation ensured that an inclusive political environment failed to form in South Korea  By appealing to the US Congress through lobbyists and other contacts in Washington, Rhee shored up his own image at the expense of the USMGIK, which only served to exacerbate the existing tensions between USMGIK and Rhee.

It is also true that command and control issues plagued the American decision makers, as Hodge and the State Department held differing opinions about how to best handle Korea. This divergence became especially noticeable in 1946 and into 1947 as Washington made key decisions about how to best interact with the Soviets over the Korean issue. Still, it is remarkable on the one hand and yet unsurprising on the other to recognize the degree to which disunity plagued the professional relationship between Hodge and Rhee after the initial months of the US occupation. It is remarkable because Rhee had, in a sense, owed much to Hodge and the USMGIK for selecting him and protecting his path to a position of power and influence within the nascent South Korean political structure, and unsurprising because, in a sense, the very agent whom the principals had selected was able to increase his influence unchecked. 

# Counterarguments and Conclusion

Some American historians, such as James Matray, have argued that the largest error in the American military occupation of Korea was the decision by the United States to select Lieutenant General Hodge as the occupation commander [see for instance, @matray_hodge_1995]. Matray's argument is that Hodge lacked the political skills and abilities to accurately read the quickly unfolding Korean political dynamics in late 1945, evident especially in Hodge's early decision to keep the Japanese colonial administrators in place. Matray further alleges that the constant decisions made by Hodge to reinforce the conservatives in the south alienated the moderates and the left, effectively eliminating any and all chance of ever forming a broad political coalition [@matray_hodge_1995]. 

After researching this paper, however, I believe Hodge's record with respect to the decisions that he made must be viewed with ample respect for the context of the unfolding Cold War in the front of our minds. Military occupations are always difficult endeavors, and in the case of Korea, simultaneous occupations were ongoing. In a sense, the Americans had multiple potential enemies in Korea: they had to navigate the minefields of Korean public opinion while attempting to form a political environment that would be in alignment with US goals and interests, all the while reacting to a simultaneous Soviet occupation of the same land immediately to their north. The simultaneous security, political, and economic tasks facing USMGIK were monumental, and the fear of empowering communists or their sympathizers was not phantom, especially considering the geopolitical situation unfolding in Europe at the same time. It is true that Hodge made mistakes, and it is also true that Korea was his first experience with military occupations. However, his share of the blame must be carefully weighed against the complexity of the situation that he faced and the speed with which the geopolitical environment was changing. With these two considerations in mind, the criticism for Hodge ought to at least be given with caution. 

For its clarity, the principal-agent model is helpful to distinguish a primary reason for the relative success of the Soviet occupation in the north of Korea, and helps illuminate why the Americans faced a far more difficult experience in the south.  

\singlespacing
\begin{small}

\begin{table}[ht]
\caption{Principal-Agent Comparisons, Korea, 1945-1948} % title of Table
\centering % used for centering table
\begin{tabular}{|p{3cm}|p{3.5cm}|p{3.5cm}|p{5cm}|}
    \hline
    Decision/Choice & USA  & Soviet Union & Summary Comparison \\ \hline
    Strategic Goals & Create a Unified, Free, and Independent State & Create a Pro-Soviet State & The American goals were more ambitious than those of the Soviet Union. \\ \hline
    Selection of Agents & Japanese administrators, then Conservative Nationalists & Left-wing / Moderates & The Americans maintained the existing colonial Japanese bureaucracy, whereas the Soviets empowered local People's Committees, which were popular among Koreans\\ \hline
    Delegation, Monitoring, and Compliance & The US Failed to develop an effective monitoring mechanism despite multiple attempts to produce an inclusive political apparatus & The SCA gave Soviets access and influence to the Koreans in the north & The Soviets had a significant advantage over the Americans  \\
    \hline
    Relationship with Chief Agent & Syngman Rhee actively undermined Lieutenant General Hodge, fomenting anti-American sentiment and playing Washington D.C. off of Hodge & Kim Il Sung welcomed Soviet assistance and was increasingly given room to operate & The overall relationship was far more effective between the Soviets and Kim than between the Americans and Rhee \\
    \hline
\end{tabular}
\label{table:comparison} % is used to refer this table in the text
\end{table}

\end{small}
\doublespacing
During military occupations, occupation forces simultaneously fill two roles with respect to principal-agent relationships. On one hand, they serve as agents of their patron states (first layer), who expect them to accomplish a desired mission. On the other hand, they also serve as principals of their agents, the burgeoning governments of the territories they are occupying (second layer). Acting as principals, these military occupiers therefore must make important decisions. 

After World War Two, the Soviets and the Americans made drastically different selection decisions in choosing who their agents would be in the early weeks and months of their occupations. The Soviets chose to align themselves with a broad front consisting of moderate and left-wing political entities after dismantling all remnants of the Japanese colonial administrators, whereas the Americans chose to work through the Japanese colonial administrators initially, and later, empowered conservative, right-wing nationalists. In terms of delegation, monitoring, and compliance, the Soviets instituted the Soviet Civil Administration (SCA), which mirrored the structure of the North Korean People's Political Committee (NKPPC). Adopting the very same structure in the SCA, the Soviets gained access and influence into virtually every facet of developing North Korean political life, providing guidance and resources as required. On the other hand, the Americans exercised the bureaucracy of the Japanese colonial administration, which further inflamed Korean public opinion in the south. Evan after recognizing that new political solutions were required, the Americans failed to implement a lasting solution. Their efforts to form an interim legislative assembly empowered a significant number of conservatives instead of achieving the broad political they desired. The chief agent chosen by the Soviets, Kim Il Sung, had a proven pro-Soviet record. He was also young and popular among Koreans in the north. Politically skilled, Kim personally desired a relationship with the Soviets, and thus, he was willing to act in accordance with their desires. Syngman Rhee, on the other hand, while empowered by the Americans initially, worked to undermine efforts by USMGIK and Hodge. Rhee was focused on maintaining power for himself at the expense of other political factions, and he did not wish to rely on USMGIK. He accused the Americans of favoring trusteeship and of purposely delaying Korean independence. Rhee and Lieutenant General Hodge never were able to resuscitate their relationship following Rhee's trip to Washington D.C. in late 1946 - early 1947. 

As principals, the Soviets managed the relationship with their agents more effectively than the Americans did. Largely due to the fact that Soviet goals were in a sense more narrow than those of the Americans, the Soviets successfully established and implemented an effective delegation, monitoring, and compliance scheme in during their occupation whereas the Americans were simply unable to establish a similar mechanism, nor were they successful in helping form any political environment that brought together competing political factions. Proof positive of the difference in how principal-agent relationships were managed between the Soviets and the Americans can be seen in the relationship that existed between each principal and its respective chief agent. In future military occupation settings, principal-agent relationships provide a useful means of exploring both the challenges and consequences facing military occupiers. As agents of their own governments, they have a mission to accomplish. But they also must make decisions as principals in selecting agents and subsequently implementing mechanisms to delegate, monitor, and ensure compliance of these agents, who may go on to become the government of the territory being occupied. How well this relationship is managed by the principal may indicate the degree to which the occupation is successful. 
\newpage

\singlespacing






 

